// Source unique d'alertes internes V0.11 pour le Dashboard.
(function () {
    'use strict';
    var store=window.COCKPIT_SETTINGS;if(!store)return;
    var observer=null,rendering=false,timer=null;
    function parseFr(value){var p=String(value||'').split('/');if(p.length!==3)return null;var d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));d.setHours(0,0,0,0);return isNaN(d)?null:d;}
    function days(a,b){return Math.round((b-a)/86400000);}
    function money(value){return window.COCKPIT_DEVIS_CALC?window.COCKPIT_DEVIS_CALC.formatMoney(value):String(value)+' €';}
    // V0.12.1 : la carte KPI "Objectif" a été retirée du Dashboard (remplacée
    // par "Nombre de clients"), donc ce calcul ne peut plus lire un
    // pourcentage déjà affiché dans le DOM — il recalcule directement CA
    // facturé (toutes factures émises) / objectif de CA configuré.
    function computeGoalPercent(){var goal=Number(store.getSection('dashboard').revenueGoal||0),total=0,calc=window.COCKPIT_DEVIS_CALC;Object.keys(window.COCKPIT_FACTURE_DETAILS||{}).forEach(function(key){var f=window.COCKPIT_FACTURE_DETAILS[key];if(f.statutEmission==='emise'&&calc)total+=calc.computeDevisTotals(f.lignes||[]).totalTTC;});return goal?Math.round(total/goal*100):100;}
    function compute(){
        var cfg=store.getSection('alerts'),d=store.getSection('dashboard'),today=new Date();today.setHours(0,0,0,0);var result=[],seen={};
        function push(key,gravity,title,sub,href,css){if(seen[key])return;seen[key]=true;result.push({key:key,gravite:gravity,titre:title,sousTexte:sub,lien:href,classe:css||'alert-info'});}
        var calc=window.COCKPIT_DEVIS_CALC,fcalc=window.COCKPIT_FACTURE_CALC;
        if(cfg.overdueInvoice.enabled&&calc&&fcalc)Object.keys(window.COCKPIT_FACTURE_DETAILS||{}).forEach(function(key){var f=window.COCKPIT_FACTURE_DETAILS[key];if(f.statutEmission!=='emise')return;var total=calc.computeDevisTotals(f.lignes||[]).totalTTC,status=fcalc.computeStatutAffiche({statutEmission:f.statutEmission,totalTTC:total,paiements:f.paiements||[],dateEcheance:f.dateEcheance});if(status==='en-retard')push('invoice:'+key,3,'Facture en retard',(f.numero||key)+' · échéance '+(f.dateEcheance||'—'),'facture-edition.html?facture='+encodeURIComponent(key),'alert-critical');});
        if(cfg.quoteNoReply.enabled&&calc)Object.keys(window.COCKPIT_DEVIS_DETAILS||{}).forEach(function(key){var q=window.COCKPIT_DEVIS_DETAILS[key],v=calc.getActiveVersion(q);if(!v||v.statut!=='envoye')return;var date=parseFr(v.dateModification||v.dateCreation),elapsed=date?days(date,today):0;if(date&&elapsed>=Number(cfg.quoteNoReply.days||7)){var client=((window.COCKPIT_CLIENT_DETAILS||{})[v.clientSlug]||v.clientSnapshot||{}).nom||v.clientSlug||'—';push('quote:'+key,1,'Devis à relancer',key+' — '+client+' ('+elapsed+' j sans réponse)','devis-edition.html?devis='+encodeURIComponent(key),'alert-info');}});
        Object.keys(window.COCKPIT_RDV_DETAILS||{}).forEach(function(key){var r=window.COCKPIT_RDV_DETAILS[key],date=parseFr(r.date),remaining=date?days(today,date):null,closed=['realise','annule','sans_suite'].indexOf(r.statut)!==-1;if(cfg.unconfirmedAppointment.enabled&&!closed&&!(r.communication&&r.communication.confirme)&&remaining!==null&&remaining>=0&&remaining<=Number(cfg.unconfirmedAppointment.days||2))push('rdv-confirm:'+key,2,'Rendez-vous non confirmé',(r.titre||'Rendez-vous')+' — '+r.date,'fiche-rdv.html?rdv='+encodeURIComponent(key),'alert-warning');var reports=(r.historique||[]).filter(function(e){return e.type==='report';}).length;if(cfg.repeatedPostponement.enabled&&reports>=Number(cfg.repeatedPostponement.count||2))push('rdv-report:'+key,2,'Rendez-vous reporté plusieurs fois',(r.titre||'Rendez-vous')+' · '+reports+' reports','fiche-rdv.html?rdv='+encodeURIComponent(key),'alert-warning');});
        if(window.COCKPIT_TRESORERIE_CALC&&window.COCKPIT_TRESORERIE_CALC.computeSnapshot){var t=store.getSection('treasury'),h=({ 'end-month':30,'end-next-month':60,'30d':30,'60d':60,'90d':90 })[t.defaultHorizon]||30,s=window.COCKPIT_TRESORERIE_CALC.computeSnapshot(h);(s.alertes||[]).forEach(function(a,index){push('treasury:'+String(a.titre).toLowerCase(),a.niveau==='critical'?3:2,a.titre,a.sousTexte,a.lien||'tresorerie.html',a.niveau==='critical'?'alert-critical':'alert-warning');});}
        var pct=computeGoalPercent();if(cfg.lateGoal.enabled&&pct<Number(cfg.lateGoal.completionPercent||70))push('goal',1,'Objectif en retard',pct+' % atteint sur la période','analyses.html','alert-info');
        result.sort(function(a,b){return b.gravite-a.gravite||a.key.localeCompare(b.key);});return result.slice(0,Math.max(1,Number(d.maxAlerts||4)));
    }
    function icon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>';}
    function render(){var list=document.getElementById('dashboard-alerts-list'),empty=document.getElementById('dashboard-alerts-empty');if(!list||rendering)return;rendering=true;if(observer)observer.disconnect();var alerts=compute(),signature=alerts.map(function(a){return a.key;}).join('|');if(list.dataset.settingsAlertSignature!==signature||list.dataset.settingsAlertSource!=='central'){list.innerHTML='';alerts.forEach(function(a){var li=document.createElement('li'),link=document.createElement('a'),i=document.createElement('span'),body=document.createElement('div'),title=document.createElement('p'),sub=document.createElement('p'),chev=document.createElement('span');link.href=a.lien;link.className='alert-item '+a.classe;i.className='alert-icon';i.innerHTML=icon();body.className='alert-item-body';title.className='alert-item-title';title.textContent=a.titre;sub.className='alert-item-subtext';sub.textContent=a.sousTexte;chev.className='alert-chevron';chev.textContent='›';body.appendChild(title);body.appendChild(sub);link.appendChild(i);link.appendChild(body);link.appendChild(chev);li.appendChild(link);list.appendChild(li);});list.dataset.settingsAlertSignature=signature;list.dataset.settingsAlertSource='central';}if(empty)empty.style.display=alerts.length?'none':'';rendering=false;if(observer)observer.observe(list,{childList:true,subtree:true});}
    function schedule(){clearTimeout(timer);timer=setTimeout(render,0);}
    document.addEventListener('DOMContentLoaded',function(){var list=document.getElementById('dashboard-alerts-list');if(list&&window.MutationObserver){observer=new MutationObserver(function(){if(!rendering)schedule();});observer.observe(list,{childList:true,subtree:true});}schedule();document.addEventListener('change',schedule);});window.addEventListener('load',schedule);store.subscribe(schedule);
    window.COCKPIT_SETTINGS_ALERTS={compute:compute,render:render};
})();
