// Centre de paramètres V0.11 — moteur d'interface piloté par le schéma.
(function () {
    'use strict';
    var store = window.COCKPIT_SETTINGS;
    var content = document.getElementById('settings-section-content');
    if (!store || !content) return;

    var sectionMeta = {
        home: ['Vue d’accueil', 'Synthèse des réglages actifs et des informations à compléter.'],
        profile: ['Profil utilisateur', 'Identité de l’utilisateur, distincte de l’entreprise et du profil de démonstration.'],
        company: ['Entreprise', 'Identité, informations légales, banque et mentions des futurs documents.'],
        appearance: ['Apparence', 'Préférences d’affichage limitées et cohérentes avec la charte.'],
        dashboard: ['Tableau de bord et objectifs', 'Valeurs d’ouverture par défaut ; les sélecteurs du Dashboard restent utilisables temporairement.'],
        alerts: ['Alertes et notifications', 'Seuils des alertes internes. Les envois externes nécessitent un backend V1.'],
        clients: ['Clients', 'Statuts, pagination et valeurs proposées dans le CRM.'],
        agenda: ['Agenda', 'Vue, horaires, durées et statuts. Un RDV hors plage reste toujours visible.'],
        products: ['Produits / Services', 'Types, statuts et valeurs commerciales du catalogue.'],
        billing: ['Facturation et documents', 'Valeurs appliquées aux nouveaux documents ; les snapshots historiques restent figés.'],
        treasury: ['Trésorerie', 'Horizon, seuils, catégories et récurrences.'],
        analytics: ['Analyses', 'Préférences d’ouverture du cockpit d’analyse.'],
        data: ['Données et configuration', 'Import, export et réinitialisation de la configuration uniquement.'],
        security: ['Compte et sécurité', 'État honnête des fonctions locales et des fonctions réservées à la V1.']
    };

    var labels = {
        firstName:'Prénom',lastName:'Nom',jobTitle:'Fonction',email:'E-mail',phone:'Téléphone',avatar:'Initiales / avatar fictif',language:'Langue',dateFormat:'Format de date',timezone:'Fuseau horaire',
        tradeName:'Nom commercial',legalName:'Raison sociale',activity:'Activité',legalForm:'Forme juridique',logoUrl:'URL du logo',initials:'Initiales du logo',address:'Adresse',website:'Site internet',siren:'SIREN',siret:'SIRET',vatNumber:'TVA intracommunautaire',vatRegime:'Régime de TVA',vatExempt:'Franchise en base',shareCapital:'Capital social',registration:'Immatriculation',iban:'IBAN',bic:'BIC',bankName:'Banque',accountHolder:'Titulaire du compte',legalNotice:'Mentions légales',footerText:'Pied de page',showContactDetails:'Afficher les coordonnées',showBankDetails:'Afficher les informations bancaires',defaultDocumentText:'Texte par défaut',signatureText:'Zone de signature',
        density:'Densité',defaultPageSize:'Taille de liste par défaut',currency:'Devise',currencyDecimals:'Afficher les décimales',weekStartsOn:'Premier jour de la semaine',accent:'Couleur d’accent',
        defaultPeriod:'Période par défaut',customPeriodStart:'Début personnalisé',customPeriodEnd:'Fin personnalisée',revenueGoal:'Objectif de CA (€)',collectionGoal:'Objectif d’encaissement (€)',cashGoal:'Objectif de trésorerie (€)',cashHorizon:'Horizon de trésorerie',chartMonths:'Période du graphique',chartIndicator:'Indicateur graphique',showCompletedTasks:'Afficher les tâches terminées',maxAlerts:'Nombre maximal d’alertes',
        overdueInvoice:'Facture en retard',quoteNoReply:'Devis sans réponse',unconfirmedAppointment:'Rendez-vous non confirmé',repeatedPostponement:'Rendez-vous reporté plusieurs fois',upcomingHeavyCharge:'Charge importante à venir',lowCash:'Trésorerie sous un seuil',lateGoal:'Objectif en retard',enabled:'Activée',days:'Délai (jours)',count:'Nombre de reports',amount:'Seuil (€)',completionPercent:'Seuil de réalisation (%)',externalEmail:'Notification e-mail',externalPush:'Notification push',externalSms:'Notification SMS',
        statuses:'Statuts',initialStatus:'Statut initial',pageSize:'Éléments par page',followUpDays:'Délai de relance (jours)',visibleFields:'Champs visibles',customFields:'Champs personnalisés préparatoires',
        defaultView:'Vue par défaut',workingDays:'Jours travaillés',startTime:'Heure de début',endTime:'Heure de fin',use24Hour:'Mode 24 heures',slotMinutes:'Pas horaire (minutes)',defaultDurationMinutes:'Durée de RDV par défaut (minutes)',confirmationDays:'Délai de confirmation (jours)',showWeekends:'Afficher les week-ends',
        types:'Types',defaultVat:'TVA par défaut (%)',defaultUnit:'Unité par défaut',paymentTerms:'Modalités de paiement',quoteAllowedStatuses:'Statuts autorisés dans les devis',families:'Familles préparatoires',
        quotePrefix:'Préfixe Devis',invoicePrefix:'Préfixe Facture',startingCounter:'Compteur de départ indicatif',includeYear:'Inclure l’année',quoteValidityDays:'Validité du devis (jours)',defaultPaymentDays:'Délai de paiement (jours)',defaultDepositPercent:'Acompte par défaut (%)',indicativeMaxDiscountPercent:'Remise maximale indicative (%)',acceptedPaymentMethods:'Moyens de paiement acceptés',latePenaltyText:'Pénalités de retard',collectionFee:'Indemnité forfaitaire (€)',showIssuerDetails:'Afficher l’émetteur',quoteSignature:'Signature du devis',
        defaultHorizon:'Horizon par défaut',lowCashThreshold:'Seuil de trésorerie (€)',heavyChargeThreshold:'Seuil de charge importante (€)',projectionMode:'Projection',categories:'Catégories d’opérations',recurrences:'Récurrences proposées',includeIssuedInvoices:'Prendre en compte les factures émises',showRealized:'Afficher les opérations réalisées',showForecast:'Afficher les opérations prévues',
        defaultTab:'Onglet ouvert',visibleIndicators:'Indicateurs visibles',comparePreviousPeriod:'Comparer à la période précédente',rankingClientCount:'Nombre de clients dans les classements',automaticFindingThreshold:'Seuil des constats automatiques (%)',showCharts:'Afficher les graphiques',showFunnels:'Afficher les tunnels'
    };

    var options = {
        language:[['fr','Français (préparatoire)'],['en','English (préparatoire)']],dateFormat:[['DD/MM/YYYY','JJ/MM/AAAA'],['YYYY-MM-DD','AAAA-MM-JJ'],['MM/DD/YYYY','MM/JJ/AAAA']],timezone:[['Europe/Paris','Europe/Paris'],['Europe/Brussels','Europe/Brussels'],['Europe/London','Europe/London'],['UTC','UTC']],density:[['comfortable','Confortable'],['compact','Compacte']],defaultPageSize:[[5,'5'],[10,'10'],[25,'25']],pageSize:[[5,'5'],[10,'10'],[25,'25']],currency:[['EUR','EUR — euro']],weekStartsOn:[['monday','Lundi'],['sunday','Dimanche']],accent:[['blue','Bleu'],['green','Vert'],['purple','Violet'],['orange','Orange'],['slate','Ardoise']],defaultPeriod:[['month','Mois en cours'],['30d','30 derniers jours'],['quarter','Trimestre en cours'],['custom','Période personnalisée']],cashHorizon:[['end-month','Fin du mois'],['end-next-month','Fin du mois suivant'],['30d','30 jours'],['60d','60 jours'],['90d','90 jours']],defaultHorizon:[['end-month','Fin du mois'],['end-next-month','Fin du mois suivant'],['30d','30 jours'],['60d','60 jours'],['90d','90 jours']],chartMonths:[[6,'6 mois'],[12,'12 mois']],chartIndicator:[['ca_facture','CA facturé'],['encaisse','Encaissé'],['solde_net','Solde net']],defaultView:[['day','Jour'],['week','Semaine'],['month','Mois'],['list','Liste']],slotMinutes:[[15,'15'],[30,'30'],[60,'60']],defaultDurationMinutes:[[15,'15'],[30,'30'],[45,'45'],[60,'60'],[90,'90'],[120,'120']],vatRegime:[['reel-normal','Réel normal'],['reel-simplifie','Réel simplifié'],['franchise','Franchise en base']],defaultUnit:[['unite','Unité'],['heure','Heure'],['jour','Jour'],['mois','Mois'],['forfait','Forfait']],projectionMode:[['30d','30 jours'],['60d','60 jours'],['90d','90 jours'],['end-month','Fin de mois']],defaultTab:[['overview','Vue d’ensemble'],['commercial','Commercial'],['clients','Clients'],['activity','Activité'],['treasury','Trésorerie']]
    };

    var section = 'home', draft = null, dirty = false, highlightPath = null;
    var title = document.getElementById('settings-section-title');
    var description = document.getElementById('settings-section-description');
    var actions = document.getElementById('settings-section-actions');
    var save = document.getElementById('settings-save');
    var reset = document.getElementById('settings-reset-section');
    var dirtyBadge = document.getElementById('settings-dirty-badge');
    var validation = document.getElementById('settings-validation-summary');
    var searchInput = document.getElementById('settings-search');
    var searchResults = document.getElementById('settings-search-results');
    var overlay = document.getElementById('settings-modal-overlay');
    var modalTitle = document.getElementById('settings-modal-title');
    var modalBody = document.getElementById('settings-modal-body');
    var modalFooter = document.getElementById('settings-modal-footer');
    var toast = document.getElementById('settings-toast');

    function clone(v){return JSON.parse(JSON.stringify(v));}
    function esc(v){return String(v==null?'':v).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
    function label(k){return labels[k]||k.replace(/([A-Z])/g,' $1').replace(/^./,function(c){return c.toUpperCase();});}
    function get(obj,path){return path.split('.').reduce(function(v,k){return v==null?undefined:v[k];},obj);}
    function set(obj,path,value){var p=path.split('.'),t=obj;p.forEach(function(k,i){if(i===p.length-1)t[k]=value;else{t[k]=t[k]||{};t=t[k];}});}
    function markDirty(){dirty=true;save.disabled=false;dirtyBadge.hidden=false;validation.hidden=true;}
    function markClean(){dirty=false;save.disabled=true;dirtyBadge.hidden=true;validation.hidden=true;}
    function notify(message,error){toast.textContent=message;toast.classList.toggle('settings-toast-error',!!error);toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(function(){toast.hidden=true;},3000);}
    function closeModal(){overlay.hidden=true;}
    function openModal(head,body,buttons){modalTitle.textContent=head;modalBody.innerHTML=body;modalFooter.innerHTML='';buttons.forEach(function(b){var n=document.createElement('button');n.type='button';n.className=b.primary?'btn-primary':'btn-secondary';n.textContent=b.label;n.onclick=b.action;modalFooter.appendChild(n);});overlay.hidden=false;}
    document.getElementById('settings-modal-close').onclick=closeModal;overlay.onclick=function(e){if(e.target===overlay)closeModal();};

    function renderHome(){var s=store.get();var cards=[['Entreprise',s.company.legalName||'À compléter','company'],['Profil actif',(s.demo.enabled?'Démo : '+s.demo.firstName+' '+s.demo.lastName:s.profile.firstName+' '+s.profile.lastName),'profile'],['Objectif mensuel',s.dashboard.revenueGoal+' €','dashboard'],['Agenda',s.agenda.defaultView+' · '+s.agenda.startTime+'–'+s.agenda.endTime,'agenda'],['Facturation',s.billing.quotePrefix+' / '+s.billing.invoicePrefix,'billing'],['Stockage','Navigateur actuel uniquement','data']];content.innerHTML='<div class="settings-home-grid">'+cards.map(function(c){return '<article class="settings-summary-card"><span>'+esc(c[0])+'</span><strong>'+esc(c[1])+'</strong><a href="#'+c[2]+'">Modifier</a></article>';}).join('')+'</div><div class="settings-form-card" style="margin-top:16px"><h3>État de configuration</h3><p class="settings-card-hint">'+(!s.company.siret||!s.profile.email?'Des informations essentielles restent à compléter.':'Les informations essentielles sont renseignées.')+'</p><p class="settings-readonly">Schéma v'+store.getSchemaVersion()+' · configuration locale · aucune donnée métier incluse</p></div>';}

    function listEditor(path,list){return '<div class="settings-field settings-field-full settings-list-editor" data-setting-anchor="'+path+'"><div class="settings-list-toolbar"><div><span class="settings-field-label">'+esc(label(path.split('.').pop()))+'</span><p class="settings-field-help">Désactivez une valeur au lieu de la supprimer pour préserver les données existantes.</p></div><button type="button" class="btn-secondary" data-add="'+path+'">Ajouter</button></div><div class="settings-list">'+list.map(function(item,i){return '<div class="settings-list-row'+(item.active===false?' settings-list-row-disabled':'')+'" data-row="'+path+'" data-index="'+i+'"><span class="settings-list-order">'+(i+1)+'</span><input data-list-key="label" value="'+esc(item.label)+'"><select data-list-key="color">'+['neutral','info','success','warning','danger'].map(function(c){return '<option value="'+c+'"'+(item.color===c?' selected':'')+'>'+c+'</option>';}).join('')+'</select><label class="settings-toggle"><input type="checkbox" data-list-key="active"'+(item.active!==false?' checked':'')+'><span>Actif</span></label><div class="settings-list-actions"><button type="button" class="settings-icon-btn" data-move="up">↑</button><button type="button" class="settings-icon-btn" data-move="down">↓</button></div></div>';}).join('')+'</div></div>';}

    function inputField(path,key,value){var type=typeof value,opts=options[key],id='setting-'+path.replace(/\./g,'-'),html='',full=['address','legalNotice','footerText','defaultDocumentText','signatureText','latePenaltyText','quoteSignature'].indexOf(key)!==-1;if(type==='boolean'){html='<label class="settings-toggle"><input id="'+id+'" type="checkbox" data-path="'+path+'"'+(value?' checked':'')+'><span>'+esc(label(key))+'</span></label>';return '<div class="settings-field'+(full?' settings-field-full':'')+'" data-setting-anchor="'+path+'">'+html+'</div>';}if(opts){html='<select id="'+id+'" data-path="'+path+'">'+opts.map(function(o){return '<option value="'+esc(o[0])+'"'+(String(o[0])===String(value)?' selected':'')+'>'+esc(o[1])+'</option>';}).join('')+'</select>';}else if(type==='number'){html='<input id="'+id+'" type="number" data-path="'+path+'" value="'+esc(value)+'">';}else if(/Time$/.test(key)){html='<input id="'+id+'" type="time" data-path="'+path+'" value="'+esc(value)+'">';}else if(/Start$|End$/.test(key)&&path.indexOf('customPeriod')!==-1){html='<input id="'+id+'" type="date" data-path="'+path+'" value="'+esc(value)+'">';}else if(full){html='<textarea id="'+id+'" data-path="'+path+'">'+esc(value)+'</textarea>';}else{var inputType=key==='email'?'email':key==='phone'?'tel':key==='logoUrl'?'url':'text';html='<input id="'+id+'" type="'+inputType+'" data-path="'+path+'" value="'+esc(value)+'">';}return '<div class="settings-field'+(full?' settings-field-full':'')+'" data-setting-anchor="'+path+'"><label for="'+id+'">'+esc(label(key))+'</label>'+html+(key==='startingCounter'?'<p class="settings-field-help">Indicatif uniquement : sans backend, la séquence comptable n’est pas garantie.</p>':'')+'</div>';}

    function renderObject(obj,prefix){var simple=[],nested=[];Object.keys(obj).forEach(function(key){if(Array.isArray(obj[key])||(obj[key]&&typeof obj[key]==='object'))nested.push(key);else simple.push(key);});var html=simple.map(function(key){if(section==='alerts'&&/^external/.test(key))return '<div class="settings-field"><span class="settings-field-label">'+esc(label(key))+'</span><div class="settings-readonly settings-unavailable">Indisponible sans backend <span class="settings-unavailable-badge">V1</span></div></div>';return inputField(prefix?prefix+'.'+key:key,key,obj[key]);}).join('');nested.forEach(function(key){var value=obj[key],path=prefix?prefix+'.'+key:key;if(Array.isArray(value)){if(value.length&&typeof value[0]==='object')html+=listEditor(path,value);else html+='<div class="settings-field settings-field-full" data-setting-anchor="'+path+'"><label>'+esc(label(key))+'</label><textarea data-lines="'+path+'" placeholder="Une valeur par ligne">'+esc(value.join('\n'))+'</textarea></div>';}else{html+='<div class="settings-field settings-field-full"><span class="settings-field-label">'+esc(label(key))+'</span></div>'+renderObject(value,path);}});return html;}

    function renderForm(){content.innerHTML='<div class="settings-form-grid"><section class="settings-form-card"><h3>'+esc(sectionMeta[section][0])+'</h3><p class="settings-card-hint">Les modifications ne sont appliquées qu’après enregistrement.</p><div class="settings-card-grid">'+renderObject(draft,'')+'</div></section></div>';bind();if(highlightPath){var t=content.querySelector('[data-setting-anchor="'+highlightPath+'"]');if(t){t.classList.add('settings-highlight');t.scrollIntoView({behavior:'smooth',block:'center'});}highlightPath=null;}}

    function bind(){content.querySelectorAll('[data-path]').forEach(function(n){n.addEventListener(n.type==='checkbox'||n.tagName==='SELECT'?'change':'input',function(){var v=n.type==='checkbox'?n.checked:n.type==='number'?Number(n.value):n.value;set(draft,n.dataset.path,v);markDirty();});});content.querySelectorAll('[data-lines]').forEach(function(n){n.oninput=function(){set(draft,n.dataset.lines,n.value.split('\n').map(function(x){return x.trim();}).filter(Boolean));markDirty();};});content.querySelectorAll('[data-list-key]').forEach(function(n){n.addEventListener(n.type==='checkbox'||n.tagName==='SELECT'?'change':'input',function(){var row=n.closest('[data-row]'),list=get(draft,row.dataset.row),item=list[Number(row.dataset.index)];item[n.dataset.listKey]=n.type==='checkbox'?n.checked:n.value;markDirty();if(n.dataset.listKey==='active')renderForm();});});content.querySelectorAll('[data-move]').forEach(function(n){n.onclick=function(){var row=n.closest('[data-row]'),list=get(draft,row.dataset.row),i=Number(row.dataset.index),j=n.dataset.move==='up'?i-1:i+1;if(j<0||j>=list.length)return;var tmp=list[i];list[i]=list[j];list[j]=tmp;list.forEach(function(x,k){x.order=k+1;});markDirty();renderForm();};});content.querySelectorAll('[data-add]').forEach(function(n){n.onclick=function(){var path=n.dataset.add;openModal('Ajouter une valeur','<div class="settings-field"><label for="new-setting-label">Libellé</label><input id="new-setting-label" type="text"></div>',[{label:'Annuler',action:closeModal},{label:'Ajouter',primary:true,action:function(){var input=document.getElementById('new-setting-label'),text=input.value.trim();if(!text)return;var list=get(draft,path),base=text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'valeur',id=base,c=2;while(list.some(function(x){return x.id===id;}))id=base+'-'+c++;list.push({id:id,label:text,color:'neutral',active:true,order:list.length+1});markDirty();closeModal();renderForm();}}]);};});}

    function renderData(){content.innerHTML='<div class="settings-data-actions">'+card('Exporter','Télécharge un JSON de configuration sans données métier.','<button id="export-settings" class="btn-primary">Exporter JSON</button>')+card('Importer','Valide le schéma et refuse les propriétés inconnues.','<button id="import-settings" class="btn-secondary">Choisir un fichier</button><input id="import-file" type="file" accept="application/json,.json" hidden>')+card('Démonstration','Charge les valeurs fictives et active un profil distinct.','<button id="demo-settings" class="btn-secondary">Charger la démonstration</button>')+card('Réinitialisation','Restaure tous les réglages sans toucher aux données métier.','<button id="reset-all-settings" class="btn-secondary">Tout réinitialiser</button>')+'</div><table class="settings-version-table"><tr><td>Schéma</td><td>v'+store.getSchemaVersion()+'</td></tr><tr><td>Application</td><td>V0.11 — en revue humaine</td></tr><tr><td>Stockage</td><td>localStorage du navigateur</td></tr><tr><td>Données métier exportées</td><td>Non</td></tr></table>';document.getElementById('export-settings').onclick=exportConfig;var file=document.getElementById('import-file');document.getElementById('import-settings').onclick=function(){file.click();};file.onchange=function(){var f=file.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var data=JSON.parse(r.result),check=store.validateImport(data);if(!check.valid)throw new Error(check.errors.join('\n'));openModal('Confirmer l’import','<p>Le fichier est compatible. Toutes les sections de configuration seront remplacées. Aucune donnée métier ne sera importée.</p>',[{label:'Annuler',action:closeModal},{label:'Importer',primary:true,action:function(){store.importConfig(data);closeModal();notify('Configuration importée.');renderData();}}]);}catch(e){notify('Import refusé : '+e.message,true);}file.value='';};r.readAsText(f);};document.getElementById('demo-settings').onclick=function(){confirmAction('Charger la démonstration ?','Le profil de démonstration sera activé.',function(){store.loadDemo();notify('Valeurs de démonstration chargées.');renderData();});};document.getElementById('reset-all-settings').onclick=function(){confirmAction('Tout réinitialiser ?','Tous les réglages locaux seront restaurés. Les données métier ne sont pas concernées.',function(){store.resetAll();notify('Configuration restaurée.');renderData();});};}
    function card(h,p,a){return '<article class="settings-data-card"><h3>'+esc(h)+'</h3><p>'+esc(p)+'</p>'+a+'</article>';}
    function exportConfig(){var blob=new Blob([store.exportConfig()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cockpit-entrepreneur-configuration-v'+store.getSchemaVersion()+'.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);notify('Configuration exportée.');}
    function renderSecurity(){var p=store.getSection('profile');content.innerHTML='<div class="settings-data-actions">'+card('Identité du compte',(p.firstName+' '+p.lastName).trim()+' · '+(p.email||'E-mail non renseigné'),'<div class="settings-readonly">Rôle fictif : '+esc(p.jobTitle||'Utilisateur')+'</div>')+card('État local','Aucune session distante ni synchronisation.','<div class="settings-readonly">Navigateur actuel uniquement</div>')+card('Mot de passe et double authentification','Nécessitent un backend sécurisé.','<div class="settings-readonly settings-unavailable">Indisponible <span class="settings-unavailable-badge">V1</span></div>')+card('Sessions, appareils et permissions','Aucun mécanisme n’est simulé dans la V0.','<div class="settings-readonly settings-unavailable">Indisponible <span class="settings-unavailable-badge">V1</span></div>')+'</div>';}
    function confirmAction(head,text,action){openModal(head,'<p>'+esc(text)+'</p>',[{label:'Annuler',action:closeModal},{label:'Confirmer',primary:true,action:function(){closeModal();action();}}]);}

    function validate(){var errors=[];if(section==='profile'&&(!draft.firstName||!draft.lastName))errors.push('Le prénom et le nom sont requis.');if(section==='company'&&(!draft.tradeName||!draft.legalName))errors.push('Le nom commercial et la raison sociale sont requis.');if(section==='agenda'&&draft.startTime>=draft.endTime)errors.push('L’heure de fin doit être postérieure à l’heure de début.');if(section==='dashboard'&&draft.defaultPeriod==='custom'&&(!draft.customPeriodStart||!draft.customPeriodEnd))errors.push('La période personnalisée nécessite deux dates.');return errors;}
    function saveSection(){var errors=validate();if(errors.length){validation.innerHTML='<strong>Enregistrement impossible :</strong><ul>'+errors.map(function(e){return '<li>'+esc(e)+'</li>';}).join('')+'</ul>';validation.hidden=false;return;}try{store.updateSection(section,draft);draft=store.getSection(section);markClean();notify('Paramètres enregistrés dans ce navigateur.');renderForm();}catch(e){notify(e.message,true);}}
    function resetSection(){confirmAction('Réinitialiser cette section ?','Les valeurs seront remplacées par les valeurs par défaut.',function(){store.resetSection(section);draft=store.getSection(section);markClean();renderForm();notify('Section réinitialisée.');});}

    function navigate(target,force){if(dirty&&!force){openModal('Modifications non enregistrées','<p>Quitter cette section supprimera les changements non enregistrés.</p>',[{label:'Rester',action:closeModal},{label:'Quitter sans enregistrer',primary:true,action:function(){closeModal();dirty=false;navigate(target,true);}}]);return;}section=sectionMeta[target]?target:'home';location.hash=section;document.querySelectorAll('[data-section-link]').forEach(function(a){a.classList.toggle('settings-nav-active',a.dataset.sectionLink===section);});title.textContent=sectionMeta[section][0];description.textContent=sectionMeta[section][1];actions.style.display=['home','data','security'].indexOf(section)===-1?'':'none';markClean();if(section==='home')renderHome();else if(section==='data')renderData();else if(section==='security')renderSecurity();else{draft=store.getSection(section);renderForm();}}

    document.querySelectorAll('[data-section-link]').forEach(function(a){a.onclick=function(e){e.preventDefault();navigate(a.dataset.sectionLink);};});content.onclick=function(e){var a=e.target.closest('a[href^="#"]');if(a){e.preventDefault();navigate(a.getAttribute('href').slice(1));}};save.onclick=saveSection;reset.onclick=resetSection;

    var searchIndex=[];Object.keys(store.getDefaults()).forEach(function(sec){if(sec==='schemaVersion')return;function walk(obj,prefix){Object.keys(obj).forEach(function(k){var path=prefix?prefix+'.'+k:k,v=obj[k];searchIndex.push({section:sec,path:path,text:(sectionMeta[sec][0]+' '+label(k)+' '+path).toLowerCase(),label:label(k)});if(v&&typeof v==='object'&&!Array.isArray(v))walk(v,path);});}walk(store.getDefaults()[sec],'');});
    searchInput.oninput=function(){var q=searchInput.value.trim().toLowerCase();if(!q){searchResults.hidden=true;return;}var found=searchIndex.filter(function(x){return x.text.indexOf(q)!==-1;}).slice(0,10);searchResults.innerHTML=found.length?found.map(function(x,i){return '<button class="settings-search-result" data-result="'+i+'"><strong>'+esc(x.label)+'</strong><span>'+esc(sectionMeta[x.section][0]+' · '+x.path)+'</span></button>';}).join(''):'<div class="settings-readonly">Aucun réglage trouvé.</div>';searchResults.hidden=false;searchResults.querySelectorAll('[data-result]').forEach(function(b){b.onclick=function(){var x=found[Number(b.dataset.result)];highlightPath=x.path;searchInput.value='';searchResults.hidden=true;navigate(x.section);};});};
    document.addEventListener('click',function(e){if(!searchResults.contains(e.target)&&e.target!==searchInput)searchResults.hidden=true;});window.addEventListener('beforeunload',function(e){if(dirty){e.preventDefault();e.returnValue='';}});window.addEventListener('hashchange',function(){var h=location.hash.slice(1)||'home';if(h!==section)navigate(h);});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!overlay.hidden)closeModal();});
    navigate(location.hash.slice(1)||'home',true);
})();
